### ISSUE TITLE
Installing from source dist does not work

### ISSUE THREAD

**Issue by almarklein** [almarklein/wgpu-py#38] opened 2020-01-14 16:07 UTC
Because it tries to open LICENSE.txt and/or README.md. Also, the front page on pypi for wgpu-py does not look so well.

**Comment by Korijn** [comment] 2020-01-14 17:37
Any ideas on resolving this?

**Comment by almarklein** [comment] 2020-01-15 07:43
yeah, I'll do something similar as we did with python-shader.

**Comment by Korijn** [comment] 2020-01-15 07:54
did you upload the sdist to pypi manually perhaps using `python setup.py upload`? Because only twine supports uploading markdown readme's apparently :/

**Comment by almarklein** [comment] 2020-01-15 08:20
there's no sdist on pypi yet, but yeah, `python setup.py sdist upload` is what generally works.

**Comment by Korijn** [comment] 2020-01-15 08:25
Well, except that that won't support markdown READMEs according to the pypa docs?

**Comment by almarklein** [comment] 2020-01-15 08:49
Ah ... I think this is because I use rst for the `long_description`, because I just use a short text - at some point I gave up on trying to make it use the README.

**Closed** 2020-01-15 09:11 UTC

**Comment by Korijn** [comment] 2020-01-15 09:14
For future reference: this was the cause Don't include the LICENSE file in the license kwarg, see pypa/setuptools#1390
